CREATE TABLE IF NOT EXISTS categories (
  id BIGINT NOT NULL UNIQUE GENERATED ALWAYS AS IDENTITY,
  guid UUID NOT NULL PRIMARY KEY,
  name VARCHAR(255) NOT NULL UNIQUE,
  created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW()
);

--bun:split

CREATE TABLE IF NOT EXISTS products(
  id BIGINT NOT NULL UNIQUE GENERATED ALWAYS AS IDENTITY,
  guid UUID NOT NULL PRIMARY KEY,
  name VARCHAR(255) NOT NULL UNIQUE,
  description VARCHAR(255) DEFAULT NULL,
  price DECIMAL(12,3) NOT NULL,
  category_guid UUID NOT NULL REFERENCES categories(guid) ON DELETE RESTRICT,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);