CREATE TABLE categories IF NOT EXISTS(
  id BIGINT NOT NULL UNIQUE,
  guid UUID NOT NULL PRIMARY KEY,
  name VARCHAR(255) NOT NULL UNIQUE,
  created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW()
);

--bun:split

CREATE TABLE products IF NOT EXISTS(
  id BIGINT NOT NULL UNIQUE,
  guid UUID NOT NULL PRIMARY KEY,
  name VARCHAR(255) NOT NULL UNIQUE,
  description VARCHAR(255) DEFAULT NULL,
  price DECIMAL(12,3) NOT NULL,
  category_guid UUID NOT NULL FOREIGN KEY,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);