// Code generated by mockery. DO NOT EDIT.

package pproduct

import (
	context "context"

	entity "github.com/badAkne/catalog-service/internal/app/entity"
	mock "github.com/stretchr/testify/mock"

	uuid "github.com/google/uuid"
)

// MockRepository is an autogenerated mock type for the Product type
type MockRepository struct {
	mock.Mock
}

type MockRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockRepository) EXPECT() *MockRepository_Expecter {
	return &MockRepository_Expecter{mock: &_m.Mock}
}

// Create provides a mock function with given fields: ctx, product
func (_m *MockRepository) Create(ctx context.Context, product entity.Product) (entity.Product, error) {
	ret := _m.Called(ctx, product)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 entity.Product
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, entity.Product) (entity.Product, error)); ok {
		return rf(ctx, product)
	}
	if rf, ok := ret.Get(0).(func(context.Context, entity.Product) entity.Product); ok {
		r0 = rf(ctx, product)
	} else {
		r0 = ret.Get(0).(entity.Product)
	}

	if rf, ok := ret.Get(1).(func(context.Context, entity.Product) error); ok {
		r1 = rf(ctx, product)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockRepository_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type MockRepository_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - product entity.Product
func (_e *MockRepository_Expecter) Create(ctx interface{}, product interface{}) *MockRepository_Create_Call {
	return &MockRepository_Create_Call{Call: _e.mock.On("Create", ctx, product)}
}

func (_c *MockRepository_Create_Call) Run(run func(ctx context.Context, product entity.Product)) *MockRepository_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(entity.Product))
	})
	return _c
}

func (_c *MockRepository_Create_Call) Return(_a0 entity.Product, _a1 error) *MockRepository_Create_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockRepository_Create_Call) RunAndReturn(run func(context.Context, entity.Product) (entity.Product, error)) *MockRepository_Create_Call {
	_c.Call.Return(run)
	return _c
}

// Delete provides a mock function with given fields: ctx, guid
func (_m *MockRepository) Delete(ctx context.Context, guid uuid.UUID) error {
	ret := _m.Called(ctx, guid)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) error); ok {
		r0 = rf(ctx, guid)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockRepository_Delete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Delete'
type MockRepository_Delete_Call struct {
	*mock.Call
}

// Delete is a helper method to define mock.On call
//   - ctx context.Context
//   - guid uuid.UUID
func (_e *MockRepository_Expecter) Delete(ctx interface{}, guid interface{}) *MockRepository_Delete_Call {
	return &MockRepository_Delete_Call{Call: _e.mock.On("Delete", ctx, guid)}
}

func (_c *MockRepository_Delete_Call) Run(run func(ctx context.Context, guid uuid.UUID)) *MockRepository_Delete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID))
	})
	return _c
}

func (_c *MockRepository_Delete_Call) Return(_a0 error) *MockRepository_Delete_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockRepository_Delete_Call) RunAndReturn(run func(context.Context, uuid.UUID) error) *MockRepository_Delete_Call {
	_c.Call.Return(run)
	return _c
}

// Get provides a mock function with given fields: ctx, guid
func (_m *MockRepository) Get(ctx context.Context, guid uuid.UUID) (entity.Product, error) {
	ret := _m.Called(ctx, guid)

	if len(ret) == 0 {
		panic("no return value specified for Get")
	}

	var r0 entity.Product
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) (entity.Product, error)); ok {
		return rf(ctx, guid)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) entity.Product); ok {
		r0 = rf(ctx, guid)
	} else {
		r0 = ret.Get(0).(entity.Product)
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = rf(ctx, guid)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockRepository_Get_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Get'
type MockRepository_Get_Call struct {
	*mock.Call
}

// Get is a helper method to define mock.On call
//   - ctx context.Context
//   - guid uuid.UUID
func (_e *MockRepository_Expecter) Get(ctx interface{}, guid interface{}) *MockRepository_Get_Call {
	return &MockRepository_Get_Call{Call: _e.mock.On("Get", ctx, guid)}
}

func (_c *MockRepository_Get_Call) Run(run func(ctx context.Context, guid uuid.UUID)) *MockRepository_Get_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID))
	})
	return _c
}

func (_c *MockRepository_Get_Call) Return(_a0 entity.Product, _a1 error) *MockRepository_Get_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockRepository_Get_Call) RunAndReturn(run func(context.Context, uuid.UUID) (entity.Product, error)) *MockRepository_Get_Call {
	_c.Call.Return(run)
	return _c
}

// GetList provides a mock function with given fields: ctx, categoryGUID, minPrice, maxPrice
func (_m *MockRepository) GetList(ctx context.Context, categoryGUID uuid.UUID, minPrice float32, maxPrice float32) ([]entity.Product, error) {
	ret := _m.Called(ctx, categoryGUID, minPrice, maxPrice)

	if len(ret) == 0 {
		panic("no return value specified for GetList")
	}

	var r0 []entity.Product
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, float32, float32) ([]entity.Product, error)); ok {
		return rf(ctx, categoryGUID, minPrice, maxPrice)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, float32, float32) []entity.Product); ok {
		r0 = rf(ctx, categoryGUID, minPrice, maxPrice)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]entity.Product)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID, float32, float32) error); ok {
		r1 = rf(ctx, categoryGUID, minPrice, maxPrice)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockRepository_GetList_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetList'
type MockRepository_GetList_Call struct {
	*mock.Call
}

// GetList is a helper method to define mock.On call
//   - ctx context.Context
//   - categoryGUID uuid.UUID
//   - minPrice float32
//   - maxPrice float32
func (_e *MockRepository_Expecter) GetList(ctx interface{}, categoryGUID interface{}, minPrice interface{}, maxPrice interface{}) *MockRepository_GetList_Call {
	return &MockRepository_GetList_Call{Call: _e.mock.On("GetList", ctx, categoryGUID, minPrice, maxPrice)}
}

func (_c *MockRepository_GetList_Call) Run(run func(ctx context.Context, categoryGUID uuid.UUID, minPrice float32, maxPrice float32)) *MockRepository_GetList_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID), args[2].(float32), args[3].(float32))
	})
	return _c
}

func (_c *MockRepository_GetList_Call) Return(_a0 []entity.Product, _a1 error) *MockRepository_GetList_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockRepository_GetList_Call) RunAndReturn(run func(context.Context, uuid.UUID, float32, float32) ([]entity.Product, error)) *MockRepository_GetList_Call {
	_c.Call.Return(run)
	return _c
}

// InsideTx provides a mock function with given fields: ctx, cb
func (_m *MockRepository) InsideTx(ctx context.Context, cb func(context.Context) error) error {
	ret := _m.Called(ctx, cb)

	if len(ret) == 0 {
		panic("no return value specified for InsideTx")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, func(context.Context) error) error); ok {
		r0 = rf(ctx, cb)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockRepository_InsideTx_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'InsideTx'
type MockRepository_InsideTx_Call struct {
	*mock.Call
}

// InsideTx is a helper method to define mock.On call
//   - ctx context.Context
//   - cb func(context.Context) error
func (_e *MockRepository_Expecter) InsideTx(ctx interface{}, cb interface{}) *MockRepository_InsideTx_Call {
	return &MockRepository_InsideTx_Call{Call: _e.mock.On("InsideTx", ctx, cb)}
}

func (_c *MockRepository_InsideTx_Call) Run(run func(ctx context.Context, cb func(context.Context) error)) *MockRepository_InsideTx_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(func(context.Context) error))
	})
	return _c
}

func (_c *MockRepository_InsideTx_Call) Return(_a0 error) *MockRepository_InsideTx_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockRepository_InsideTx_Call) RunAndReturn(run func(context.Context, func(context.Context) error) error) *MockRepository_InsideTx_Call {
	_c.Call.Return(run)
	return _c
}

// IsExistWithName provides a mock function with given fields: ctx, name
func (_m *MockRepository) IsExistWithName(ctx context.Context, name string) error {
	ret := _m.Called(ctx, name)

	if len(ret) == 0 {
		panic("no return value specified for IsExistWithName")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = rf(ctx, name)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockRepository_IsExistWithName_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'IsExistWithName'
type MockRepository_IsExistWithName_Call struct {
	*mock.Call
}

// IsExistWithName is a helper method to define mock.On call
//   - ctx context.Context
//   - name string
func (_e *MockRepository_Expecter) IsExistWithName(ctx interface{}, name interface{}) *MockRepository_IsExistWithName_Call {
	return &MockRepository_IsExistWithName_Call{Call: _e.mock.On("IsExistWithName", ctx, name)}
}

func (_c *MockRepository_IsExistWithName_Call) Run(run func(ctx context.Context, name string)) *MockRepository_IsExistWithName_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockRepository_IsExistWithName_Call) Return(_a0 error) *MockRepository_IsExistWithName_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockRepository_IsExistWithName_Call) RunAndReturn(run func(context.Context, string) error) *MockRepository_IsExistWithName_Call {
	_c.Call.Return(run)
	return _c
}

// Update provides a mock function with given fields: ctx, product
func (_m *MockRepository) Update(ctx context.Context, product entity.Product) (entity.Product, error) {
	ret := _m.Called(ctx, product)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 entity.Product
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, entity.Product) (entity.Product, error)); ok {
		return rf(ctx, product)
	}
	if rf, ok := ret.Get(0).(func(context.Context, entity.Product) entity.Product); ok {
		r0 = rf(ctx, product)
	} else {
		r0 = ret.Get(0).(entity.Product)
	}

	if rf, ok := ret.Get(1).(func(context.Context, entity.Product) error); ok {
		r1 = rf(ctx, product)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockRepository_Update_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Update'
type MockRepository_Update_Call struct {
	*mock.Call
}

// Update is a helper method to define mock.On call
//   - ctx context.Context
//   - product entity.Product
func (_e *MockRepository_Expecter) Update(ctx interface{}, product interface{}) *MockRepository_Update_Call {
	return &MockRepository_Update_Call{Call: _e.mock.On("Update", ctx, product)}
}

func (_c *MockRepository_Update_Call) Run(run func(ctx context.Context, product entity.Product)) *MockRepository_Update_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(entity.Product))
	})
	return _c
}

func (_c *MockRepository_Update_Call) Return(_a0 entity.Product, _a1 error) *MockRepository_Update_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockRepository_Update_Call) RunAndReturn(run func(context.Context, entity.Product) (entity.Product, error)) *MockRepository_Update_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockRepository creates a new instance of MockRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockRepository {
	mock := &MockRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
